### PR TITLE
Laser skips clusters and coltan, mining drill through lava, 1% coltan

### PR DESCRIPTION
**Pull request by Zuxelus**
1) Laser Drill skips coltan and cluster blocks.
2) Mining Drill extracts coltan with 1% chance on try to be extracted.
3) Both drills cannot break coltan block.
4) Mining drill can replace center lava block with drill pipe block and doesn't stop.

### CODE REVIEW

**Comment by TheOriginalGolem** [comment]
will look at later

**Comment by TheOriginalGolem** [comment]
> 1. Laser Drill skips coltan and cluster blocks.
> 2. Mining Drill extracts coltan with 1% chance on try to be extracted.
> 3. Both drills cannot break coltan block.
> 4. Mining drill can replace center lava block with drill pipe block and doesn't stop.

Sorry for the very late reply, is this inline with 1.7's behaviour?

**Comment by Zuxelus** [comment]
I didn't check 1.7. This modification is done based on The Bobcat answers in Discord.

The Bobcat — 08/14/2022
the entire point of bedrock ore is that it's an infinite source of coltan but it's rather slow

**Comment by mexikoedi** [comment]
The changes at "src/main/java/com/hbm/blocks/generic/BlockBedrockOre.java" are not inline with 1.7 behavior.
(I didn't check the other files.)

The specific 1.7 code can be seen here: 
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/master/src/main/java/com/hbm/blocks/generic/BlockBedrockOre.java

**Comment by Zuxelus** [comment]
Why should it be inline with 1.7? It is done based on 1.7 mod author answers on how it should work. Seems that this part is not done in 1.7 yet.

**Comment by TheOriginalGolem** [comment]
Closing due to it deviating from 1.7

**Pull request closed without merging**
